### ISSUE TITLE
Should we integrate whitelist support.

### ISSUE THREAD

**Issue by indepth666** [indepth666/py3rcon#12]
I would like to integrate some kind of whitelist support.
It could be used to prevent new user(hacker?) on busy night on popular server.
I think it should be possible to turn it on/off by admin in global chat.

What would be the best database to save the guid. I like sqlite on linux for this but I don't know how it would work under windows.

**Comment by ole1986** [comment]
Json file are becoming famous.. Why not use a whitelist.json file?

**Comment by indepth666** [comment]
could be nice but how is the performance of json with 10,000+ entry?

**Comment by ole1986** [comment]
I think so - *.pyc is even compiled. and we are talking about ~600kb only the UID

Just to be sure, you want a whitelist being stored and the pyrcon script is reading from it to only allow those (which are in list and kick all other) ? right?

I could then add a "whitelist" button in the GUI so its ease to add the players

**Comment by indepth666** [comment]
Exactly.

**Comment by ole1986** [comment]
I will take this issue ;-)

**Comment by indepth666** [comment]
You should also log every GUID that connect to the server. 
All GUID & playername get added to the database if they are not already with a whilisted value set to false. 
After that you can search the database and set who ever you want to be able to access the server to true.

**Comment by ole1986** [comment]
first whitelist implementation is available - feel free to test

**Usage:**
when using the configexample.json it will automatically create a whitelist.json containing all players connected to the server.

By default, all players are **BLACKLISTED** - So it is required to get into the whitelist.json and change the allowed property to "true".

**Comment by indepth666** [comment]
Seem to work good so far, will do more testing tomorow. Also seem to be running smooth with python3.
