### ISSUE TITLE
Using python 3.X instead of python 2.X

### ISSUE THREAD

**Issue by ole1986** [indepth666/py3rcon#13]
As python 2.7 was released at July 3rd, 2010 and there will be no 2.8. We should think of updating the source to work properly with python 3.X

I noted already that print and text/byte comparison is an issue for pyrcon when changing to the latest python 3 version.

I can add a new branch for py3K with all the changes made for issue  #12 if you want

**Comment by indepth666** [comment]
K. Do it and we will switch completely to py3.

**Comment by ole1986** [comment]
as a side note I have tested the current branch **py3k** with python:

Version: 2.7.9
Version: 3.5.2

Both are working!
