### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by indepth666** [indepth666/py3rcon#7]
I have modified the files for python3 compatibility. Can you do some testing to be sure everything is still working? I do not have a working server at the moment

Also, try to follow indentation standard. 

Thanks! :)

**Comment by ole1986** [comment]
Please read the below.

http://stackoverflow.com/questions/1125653/python-4-whitespaces-indention-why

Thank you

**Comment by indepth666** [comment]
I don't care if we use tab or whitespace. We just need to be consistent.
Let me know what you prefer.

Thanks

**Comment by ole1986** [comment]
Sorry, but why you have than change almost all files to use tabs instead if you dont care?
4 spaces as the community said is recommended and we should use it that way.

Now I already merged your things into my repo. So please change it back after i have tested your python3 modification.

Thanks

**Comment by indepth666** [comment]
Because sometime it was tab and sometime it was space. I just wanted to be
uniform. Python3 was throwing error when indentation was not uniform across
the file.

4 spaces it would be since I also prefer it that way. The script I used to
standardize the files was using tabulation but it will be easy to go with
space indentation instead.

Also, another point I would like to discuss with you. Maybe we could use
branching for new feature implementation. What do you think ?

Thanks again.

**Comment by ole1986** [comment]
sure, branching is a good idea and we should already do this for python 3 because many server dont have  python3 installed by default

**Comment by indepth666** [comment]
K. I think it's now standard on Debian, centos and Ubuntu but you are right
that it may be a problem on older server or bsd system. But we may be able
to be python 2.7 and 3 compatible by using newer standard.

Deprecating the use of the curved brace in print and using .format instead
would be a good start. That way we would only have one branch to maintain.

I'll try this weekend and we will see how ti goes.

**Comment by ole1986** [comment]
well just installed a brand new server with debian 8 - python 2.7 was installed by default.

So I woudl not recommend to set !#/bin/python3 - ppl will complain "its not running on my server" without checking the python version.

**Comment by ole1986** [comment]
think this issue can be closed as it is compatible with python >=2.7  and >= 3. Except issue #8
