### ISSUE TITLE
py3rcon gui not fully displayed when using python3

### ISSUE THREAD

**Issue by ole1986** [indepth666/py3rcon#8]
for some reason the curses GUI is not displayed properly when using python3 instead of python 2.7 for instance.

As a workaround please use python 2.7 until its fixed

**Comment by indepth666** [comment]
It wont display on my laptop, screen not high enough.
But otherwise very nice GUI.

I am thinking about transfering the project to you since I don't really have time to work on this at the moment, are you interested?

**Comment by ole1986** [comment]
Actually, I also have not much time to do another project...
IMO we are not in rush as we do not yet have much ppl. using it (or?).

So you can take your time to do pull request ;-)

**Comment by indepth666** [comment]
Copy clear! ☺

**Comment by ole1986** [comment]
... but that should not prevent us from advertising the new py3rcon ;-)
